version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: main.tf
      - terraform/validate:
          path: main.tf
      - terraform/fmt:
          path: main.tf
      - terraform/plan:
          path: main.tf
      - terraform/apply:
          path: main.tf
      - terraform/destroy:
          path: main.tf
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
